name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Go application
      run: cd broker-service && env GOOS=linux CGO_ENABLED=0 go build -o authApp ./cmd/api
    - name: Build Docker image
      run: docker build -t registry.digitalocean.com/lingvini/authApp:latest .
    - name: Login to DigitalOcean Registry
      run: echo ${{ secrets.DO_API_TOKEN }} | docker login -u ${{ secrets.DO_API_TOKEN }} --password-stdin registry.digitalocean.com
    - name: Push to DigitalOcean Registry
      run: docker push registry.digitalocean.com/lingvini/authApp:latest
