name: Build and Push Docker Image to DockerHub
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Build brokerApp application
      run: cd broker-service && env GOOS=linux CGO_ENABLED=0 go build -o brokerApp ./cmd/api
    - name: Build brokerApp Docker image
      run: cd broker-service && docker build -t arkadiyagapov/linguini/brokerapp:latest . -f broker-service.dockerfile
    - name: Build authApp application
      run: cd authentication-service && env GOOS=linux CGO_ENABLED=0 go build -o authApp ./cmd/api
    - name: Build authApp Docker image
      run: cd authentication-service && docker build -t arkadiyagapov/linguini/authapp:latest . -f authentication-service.dockerfile
    
    - name: Login to Docker Hub
      uses: ghcr.io/actions/docker-login@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push brokerApp to DigitalOcean Registry
      run: docker push arkadiyagapov/linguini/brokerapp:latest
    - name: Push authApp to DigitalOcean Registry
      run: docker push arkadiyagapov/linguini/authapp:latest
