name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.9'
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - name: Get chi
      run: go get -u -v -f all
    - name: Get chi middlware
      run: go get github.com/go-chi/chi/v5/middleware
    - name: Get chi cors
      run: go get github.com/go-chi/cors
    - name: Build Go application
      run: cd broker-service && go build -o authApp ./cmd/api
    - name: Build Docker image
      run: docker build -t registry.digitalocean.com/lingvini/authApp:latest .
    - name: Login to DigitalOcean Registry
      run: echo ${{ secrets.DO_API_TOKEN }} | docker login -u ${{ secrets.DO_API_TOKEN }} --password-stdin registry.digitalocean.com
    - name: Push to DigitalOcean Registry
      run: docker push registry.digitalocean.com/lingvini/authApp:latest
