name: Deploy to DigitalOcean
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Copy Docker Compose to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME_LING_1 }}
        key: ${{ secrets.SSH_PRIVATE_KEY_LING_1 }}
        passphrase: ${{ secrets.SSH_PASSPHRASE_KEY_LING_1 }}
        source: ./project/docker-compose.yml
        target: /home/deployer/docker-compose.yml
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_LING_1 }}
        username: ${{ secrets.USERNAME_LING_1 }}
        key: ${{ secrets.SSH_PRIVATE_KEY_LING_1 }}
        passphrase: ${{ secrets.SSH_PASSPHRASE_KEY_LING_1 }}
        script: |
          docker-compose -f /home/deployer/docker-compose.yml down
          docker-compose -f /home/deployer/docker-compose.yml up -d
